/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2015-10-26 06:57:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"description\" content=\"\"/>\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\"/>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Favorite Icons -->\r\n");
      out.write("\t<link rel=\"icon\" href=\"img/favicon/favicon.html\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"img/favicon/apple-touch-icon-144x144-precomposed.html\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"img/favicon/apple-touch-icon-72x72-precomposed.html\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon-precomposed\" href=\"img/favicon/apple-touch-icon-precomposed.html\">\r\n");
      out.write("\t<!-- // Favorite Icons -->\r\n");
      out.write("\t\r\n");
      out.write("\t<link href='http://fonts.useso.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- GENERAL CSS FILES -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/minified.css\">\r\n");
      out.write("\t<!-- // GENERAL CSS FILES -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!--[if IE 8]>\r\n");
      out.write("\t\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/selectivizr-min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t-->\r\n");
      out.write("\t<script>window.jQuery || document.write('<script src=\"js/jquery.min.js\"><\\/script>');</script>\r\n");
      out.write("\t<script src=\"js/modernizr.min.js\"></script>\t\r\n");
      out.write("\t<!-- PARTICULAR PAGES CSS FILES -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/owl.theme.css\">\r\n");
      out.write("\t<link href=\"css/flexslider.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<!-- // PARTICULAR PAGES CSS FILES -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- SITE FOOTER -->\r\n");
      out.write("\t<footer class=\"page-footer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- WIDGET AREA -->\r\n");
      out.write("\t\t<div class=\"widgets\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- FIRST ROW -->\r\n");
      out.write("\t\t\t<div class=\"section\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<section class=\"widget widget-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"widget-title\">悦书</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>悦书是在线购书的第一品牌，包括多种新书和二手书，是您购书，品书的不二选择。我们诚挚欢迎您的光临</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"space40 visible-sm clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<section class=\"widget widget-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"widget-title\">了解我们</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"menu iconed-menu unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"iconfont-circle-blank menu-icon\"></i>人才招聘</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"iconfont-circle-blank menu-icon\"></i>物流信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"iconfont-circle-blank menu-icon\"></i>关于我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"iconfont-circle-blank menu-icon\"></i>退货政策</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<section class=\"widget widget-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"widget-title\">联系我们</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"menu iconed-list unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"list-icon\"><i class=\"round-icon iconfont-map-marker\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"list-content\">中央财经大学</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"list-icon\"><i class=\"round-icon iconfont-phone\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"list-content\">086-8008208820</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"list-icon\"><i class=\"round-icon iconfont-envelope-alt\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"list-content\">bxmn4728@163.com</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<section class=\"widget widget-subscription\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"widget-title\">Newletter</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>注册成为我们的会员，获得悦书的最新信息！！！</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"subscription-email\" class=\"placeholder\">输入您的邮箱</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" id=\"subscription-email\" name=\"email\" class=\"form-control\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\">注册</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- // FIRST ROW -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- // WIDGET AREA -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footer-sub\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-links center-xs clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">我们的地址</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">与我们合作</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"space10\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"copyright center-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>©2015WEB课程设计||<a href=https://github.com/bysuggestion/B2Cforbook“ target=\"_blank\" title=\"王幸岚WEB课设\">王幸岚</a>  ||All Rights Reserved.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"space40 visible-xs\"></div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12 col-sm-6 center-xs\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vmid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"uppercase\">Payment Accept&emsp;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/visacard.png\" alt=\"\" width=\"40\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/mastercard.png\" alt=\"\" width=\"40\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/paypal.png\" alt=\"\" width=\"40\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- // SITE FOOTER -->\r\n");
      out.write("<!-- // PAGE WRAPPER -->\r\n");
      out.write("\r\n");
      out.write("<!-- Essential Javascripts -->\r\n");
      out.write("<script src=\"js/minified.js\"></script>\r\n");
      out.write("<!-- // Essential Javascripts -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Particular Page Javascripts -->\r\n");
      out.write("\t<script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\t<!-- // Particular Page Javascripts -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
