/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2015-10-25 16:38:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>悦书</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"description\" content=\"\"/>\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\"/>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Favorite Icons -->\r\n");
      out.write("\t<link rel=\"icon\" href=\"img/favicon/favicon.html\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"img/favicon/apple-touch-icon-144x144-precomposed.html\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"img/favicon/apple-touch-icon-72x72-precomposed.html\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon-precomposed\" href=\"img/favicon/apple-touch-icon-precomposed.html\">\r\n");
      out.write("\t<!-- // Favorite Icons -->\r\n");
      out.write("\t\r\n");
      out.write("\t<link href='http://fonts.useso.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- GENERAL CSS FILES -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/minified.css\">\r\n");
      out.write("\t<!-- // GENERAL CSS FILES -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!--[if IE 8]>\r\n");
      out.write("\t\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/selectivizr-min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t-->\r\n");
      out.write("\t<script>window.jQuery || document.write('<script src=\"js/jquery.min.js\"><\\/script>');</script>\r\n");
      out.write("\t<script src=\"js/modernizr.min.js\"></script>\t\r\n");
      out.write("\t<!-- PARTICULAR PAGES CSS FILES -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/owl.theme.css\">\r\n");
      out.write("\t<link href=\"css/flexslider.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<!-- // PARTICULAR PAGES CSS FILES -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- SITE HEADER -->\r\n");
      out.write("\t<header id=\"site-header\" role=\"banner\">\r\n");
      out.write("\t\t<!-- HEADER TOP -->\r\n");
      out.write("\t\t<div class=\"header-top\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12 col-sm-6 col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t<!-- CONTACT INFO -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"contact-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"iconfont-headphones round-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>800-820-8820</strong>\r\n");
      out.write("\t\t\t\t\t\t\t<span>(Mon- Fri: 09.00 - 21.00)</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- // CONTACT INFO -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12 col-sm-6 col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"actions unstyled clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- SEARCH BOX -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"search-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-iconed prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"input-icon\"><i class=\"iconfont-search\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"input-search\" class=\"placeholder\">想找什么。。。</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"q\" id=\"input-search\"  required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- // SEARCH BOX -->\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li data-toggle=\"sub-header\" data-target=\"#sub-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- SHOPPING CART -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:void(0);\" id=\"total-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>购物车<i class=\"iconfont-shopping-cart round-icon\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"sub-cart\" class=\"sub-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cart-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>你的购物车空空如也</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small><a href=\"cart.html\">查看购物车</a></small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"cart-items product-medialist unstyled clearfix\"></ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cart-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart-total clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">总计：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right total\">¥ 0</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"cart.jsp\" class=\"btn btn-default btn-round view-cart\">购物车</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"checkout.jsp\" class=\"btn btn-default btn-round view-cart\">去结算</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- // SHOPPING CART -->\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- ADD TO CART MESSAGE -->\r\n");
      out.write("\t\t\t<div class=\"cart-notification\">\r\n");
      out.write("\t\t\t\t<ul class=\"unstyled\"></ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- // ADD TO CART MESSAGE -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- // HEADER TOP -->\r\n");
      out.write("\t\t<!-- MAIN HEADER -->\r\n");
      out.write("\t\t<div class=\"main-header-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"main-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- SITE LOGO -->\r\n");
      out.write("\t\t\t\t\t<div class=\"logo-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"index.jsp\" class=\"logo\" title=\"悦书\">\r\n");
      out.write("\t\t\t\t\t\t\t<font>悦书</font>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- // SITE LOGO -->\r\n");
      out.write("\t\t\t\t\t<!-- SITE NAVIGATION MENU -->\r\n");
      out.write("\t\t\t\t\t<nav id=\"site-menu\" role=\"navigation\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"main-menu  hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">我的悦书</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"productsList.jsp\">新书</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"productsList.jsp\">二手书</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"aboutUs.jsp\">About Us</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"login.jsp\">&nbsp;&nbsp;>>>登陆</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"register.jsp\">注册</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t<!-- // SITE NAVIGATION MENU -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- // MAIN HEADER -->\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- // SITE HEADER -->\r\n");
      out.write("\t<!-- Essential Javascripts -->\r\n");
      out.write("<script src=\"js/minified.js\"></script>\r\n");
      out.write("<!-- // Essential Javascripts -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Particular Page Javascripts -->\r\n");
      out.write("\t<script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\t<!-- // Particular Page Javascripts -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
